# Generated by Django 4.2.7 on 2023-11-23 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 11, 51, 15, 318176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_pst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_utc',
            field=models.BooleanField(default=True),
        ),
    ]
